# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        :categories/:title
paginate_path:    /page/:num
relative_permalinks: true

# Setup
title:            Learn
tagline:          'Learning Orchestra Platform'
description:      'Orchestra Platfrom 3.'
url:              http://learn.orchestraplatform.com
baseurl:          /
excerpt_separator: "<!--more-->"

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

github:
  repo:           https://github.com/orchestral/platform
