# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Learn
tagline:          'Learning Orchestra Platform'
description:      'Orchestra Platfrom 3.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

github:
  repo:           https://github.com/poole/hyde
